import React from "react";
import {ScrollView,View,Text,TextInput,Pressable,StyleSheet,TextInputProps} from "react-native";
import {router} from "expo-router";
import {C} from "../constants/palette";
export function Page({children}:{children:React.ReactNode}){return <ScrollView style={s.page} contentContainerStyle={s.body} keyboardShouldPersistTaps="handled">{children}</ScrollView>}
export function Header({title,sub,back=false}:{title:string;sub?:string;back?:boolean}){return <View style={s.header}>{back&&<Pressable onPress={()=>router.back()}><Text style={s.back}>‹</Text></Pressable>}<View style={{flex:1}}><Text style={s.title}>{title}</Text>{!!sub&&<Text style={s.sub}>{sub}</Text>}</View></View>}
export function Card({children,style}:any){return <View style={[s.card,style]}>{children}</View>}
export function Button({title,onPress,outline=false}:{title:string;onPress:()=>void;outline?:boolean}){return <Pressable onPress={onPress} style={[s.btn,outline&&s.outline]}><Text style={[s.btnText,outline&&{color:C.maroon}]}>{title}</Text></Pressable>}
export function Field({label,...p}:TextInputProps&{label:string}){return <View style={{gap:6}}><Text style={s.label}>{label}</Text><TextInput placeholderTextColor="#A49A9F" style={[s.input,p.multiline&&{height:112,paddingTop:12}]} {...p}/></View>}
export function Heading({children}:{children:string}){return <Text style={s.heading}>{children}</Text>}
export function Pill({children,color=C.maroon}:{children:string;color?:string}){return <View style={{backgroundColor:color+"18",paddingVertical:5,paddingHorizontal:9,borderRadius:6}}><Text style={{fontSize:10,fontWeight:"800",color}}>{children.toUpperCase()}</Text></View>}
export function Item({title,meta,status="PENDING",onPress}:{title:string;meta:string;status?:string;onPress?:()=>void}){return <Pressable onPress={onPress} style={s.item}><View style={{flex:1,gap:4}}><Text style={s.itemTitle}>{title}</Text><Text style={s.meta}>{meta}</Text></View><Pill color={status==="COMPLETED"?"#247A50":status==="IN PROGRESS"?"#245A91":C.maroon}>{status}</Pill></Pressable>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:C.bg},body:{padding:20,paddingBottom:34,gap:17},header:{flexDirection:"row",alignItems:"center",gap:10},back:{fontSize:30,color:C.maroon,paddingRight:4},title:{fontSize:23,fontWeight:"800",color:C.ink},sub:{fontSize:13,color:C.muted,marginTop:3},card:{backgroundColor:"#fff",borderRadius:16,borderWidth:1,borderColor:C.line,padding:16,gap:13},btn:{backgroundColor:C.maroon,minHeight:47,borderRadius:11,alignItems:"center",justifyContent:"center",paddingHorizontal:15},outline:{backgroundColor:"#fff",borderWidth:1,borderColor:C.maroon},btnText:{color:"#fff",fontSize:14,fontWeight:"800"},label:{color:C.ink,fontWeight:"700",fontSize:13},input:{minHeight:46,borderWidth:1,borderColor:C.line,borderRadius:10,paddingHorizontal:12,backgroundColor:"#fff",color:C.ink,fontSize:14},heading:{fontSize:16,fontWeight:"800",color:C.ink},item:{paddingVertical:12,borderBottomWidth:1,borderBottomColor:"#F0EAED",flexDirection:"row",alignItems:"center",gap:10},itemTitle:{fontSize:14,fontWeight:"700",color:C.ink},meta:{fontSize:11,color:C.muted}});
